# Generated by Django 3.2 on 2021-05-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_rename_marca_id_modelo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_practica', models.CharField(max_length=70)),
                ('ano', models.CharField(max_length=70)),
                ('semestre', models.CharField(max_length=70)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.carrera')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=20)),
                ('cantidad_horas', models.CharField(max_length=70)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resgistrolab.curso')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resgistrolab.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=70)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resgistrolab.prestamolaboratorio')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.sexo')),
            ],
        ),
    ]
