# Generated by Django 3.2 on 2021-05-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_modelo_marca_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='marca_id',
            new_name='marca',
        ),
    ]
