# Generated by Django 3.2 on 2021-05-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_rename_marca_id_modelo_marca'),
        ('resgistrolab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=70)),
                ('fecha', models.DateField(max_length=20)),
                ('hora_inicio', models.TimeField(max_length=30)),
                ('hora_fin', models.TimeField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.area')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.carrera')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.modalidad')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resgistrolab.usuario')),
            ],
        ),
    ]
