# Generated by Django 3.2 on 2021-05-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent_equipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='equipo',
            new_name='detalle',
        ),
        migrations.AddField(
            model_name='equipo',
            name='padre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent_equipo.equipo'),
        ),
    ]
