# Generated by Django 3.2 on 2021-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_equipo', '0003_rename_detalle_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cod_inventario',
            field=models.IntegerField(),
        ),
    ]
